#include <iostream>
#include <limits>
#include <algorithm>
#include "static_string.h"

using namespace snw1;

int main() {
    { // make() simple tests
        constexpr char c[] = "abc";
        constexpr auto s = static_string::make(c);
        static_assert(s == "abc", "");
    }

    // operator _ss() tests
    static_assert(""_ss == "", "");
    static_assert("H"_ss == "H", "");
    static_assert("Hello"_ss == "Hello", "");
    static_assert("Hello world"_ss == "Hello world", "");

    // sizeof() tests
    static_assert(sizeof(""_ss) == 1, "");
    static_assert(sizeof("H"_ss) == 2, "");
    static_assert(sizeof("Hello"_ss) == 6, "");
    static_assert(sizeof("Hello world"_ss) == 12, "");

    // comparison operators tests
    static_assert(""_ss == "", "");
    static_assert("" == ""_ss, "");
    static_assert(""_ss == ""_ss, "");
    static_assert(""_ss < "Hello", "");
    static_assert("" < "Hello"_ss, "");
    static_assert(""_ss < "Hello"_ss, "");
    static_assert("Hello"_ss > "", "");
    static_assert("Hello" > ""_ss, "");
    static_assert("Hello"_ss > ""_ss, "");
    static_assert("Hello"_ss == "Hello", "");
    static_assert("Hello" == "Hello"_ss, "");
    static_assert("Hello"_ss == "Hello"_ss, "");
    static_assert("Hell"_ss < "Hello", "");
    static_assert("Hell" < "Hello"_ss, "");
    static_assert("Hell"_ss < "Hello"_ss, "");
    static_assert("Hello"_ss > "Hell", "");
    static_assert("Hello" > "Hell"_ss, "");
    static_assert("Hello"_ss > "Hell"_ss, "");
    static_assert("Hella"_ss < "Hello", "");
    static_assert("Hella" < "Hello"_ss, "");
    static_assert("Hella"_ss < "Hello"_ss, "");
    static_assert("Hello"_ss > "Hella", "");
    static_assert("Hello" > "Hella"_ss, "");
    static_assert("Hello"_ss > "Hella"_ss, "");
    static_assert(""_ss != "Hello", "");
    static_assert("" != "Hello"_ss, "");
    static_assert(""_ss != "Hello"_ss, "");
    static_assert("Hello"_ss != "", "");
    static_assert("Hello" != ""_ss, "");
    static_assert("Hello"_ss != ""_ss, "");
    static_assert("Hell"_ss != "Hello", "");
    static_assert("Hell" != "Hello"_ss, "");
    static_assert("Hell"_ss != "Hello"_ss, "");
    static_assert("Hello"_ss != "Hell", "");
    static_assert("Hello" != "Hell"_ss, "");
    static_assert("Hello"_ss != "Hell"_ss, "");
    static_assert("Hella"_ss != "Hello", "");
    static_assert("Hella" != "Hello"_ss, "");
    static_assert("Hella"_ss != "Hello"_ss, "");
    static_assert("Hello"_ss != "Hella", "");
    static_assert("Hello" != "Hella"_ss, "");
    static_assert("Hello"_ss != "Hella"_ss, "");
    static_assert(""_ss <= "", "");
    static_assert("" >= ""_ss, "");
    static_assert(""_ss <= ""_ss, "");
    static_assert(""_ss <= "Hello", "");
    static_assert("" <= "Hello"_ss, "");
    static_assert(""_ss <= "Hello"_ss, "");
    static_assert("Hello"_ss >= "", "");
    static_assert("Hello" >= ""_ss, "");
    static_assert("Hello"_ss >= ""_ss, "");
    static_assert("Hello"_ss <= "Hello", "");
    static_assert("Hello" >= "Hello"_ss, "");
    static_assert("Hello"_ss <= "Hello"_ss, "");
    static_assert("Hell"_ss <= "Hello", "");
    static_assert("Hell" <= "Hello"_ss, "");
    static_assert("Hell"_ss <= "Hello"_ss, "");
    static_assert("Hello"_ss >= "Hell", "");
    static_assert("Hello" >= "Hell"_ss, "");
    static_assert("Hello"_ss >= "Hell"_ss, "");
    static_assert("Hella"_ss <= "Hello", "");
    static_assert("Hella" <= "Hello"_ss, "");
    static_assert("Hella"_ss <= "Hello"_ss, "");
    static_assert("Hello"_ss >= "Hella", "");
    static_assert("Hello" >= "Hella"_ss, "");
    static_assert("Hello"_ss >= "Hella"_ss, "");

    // make() concat tests
    static_assert(static_string::make() == "", "");
    static_assert(static_string::make("") == "", "");
    static_assert(static_string::make("", "") == "", "");
    static_assert(static_string::make("", "", "") == "", "");
    static_assert(static_string::make("", ""_ss, "") == "", "");
    static_assert(static_string::make(""_ss, "", ""_ss) == "", "");
    static_assert(static_string::make(""_ss, ""_ss, ""_ss) == "", "");
    static_assert(static_string::make("Hello") == "Hello", "");
    static_assert(static_string::make("", "Hello") == "Hello", "");
    static_assert(static_string::make("", "Hello", "") == "Hello", "");
    static_assert(static_string::make("", "Hello"_ss, "") == "Hello", "");
    static_assert(static_string::make(""_ss, "", "Hello"_ss) == "Hello", "");
    static_assert(static_string::make("Hello"_ss, ""_ss, ""_ss) == "Hello", "");
    static_assert(static_string::make("Hello", "World") == "HelloWorld", "");
    static_assert(static_string::make("Hello"_ss, "World") == "HelloWorld", "");
    static_assert(static_string::make("Hello", "World"_ss) == "HelloWorld", "");
    static_assert(static_string::make("Hello"_ss, "World"_ss) == "HelloWorld", "");
    static_assert(static_string::make("Hello", ", ", "World", "!") == "Hello, World!", "");
    static_assert(static_string::make("Hello"_ss, ", ", "World"_ss, "!") == "Hello, World!", "");
    static_assert(static_string::make("Hello"_ss, ", "_ss, "World"_ss, "!"_ss) == "Hello, World!", "");

    // operator+() tests
    static_assert("Hello"_ss + "World" == "HelloWorld", "");
    static_assert("Hello" + "World"_ss == "HelloWorld", "");
    static_assert("Hello"_ss + "World"_ss == "HelloWorld", "");
    static_assert("Hello"_ss + ", " + "World"_ss + "!" == "Hello, World!", "");

    // reverse() tests
    static_assert(""_ss.reverse() == "", "");
    static_assert("H"_ss.reverse() == "H", "");
    static_assert("Hello"_ss.reverse() == "olleH", "");
    static_assert("Hello world"_ss.reverse() == "dlrow olleH", "");

    // substring() tests
    static_assert(""_ss.substring<0, 0>() == "", "");
    static_assert("H"_ss.substring<0, 0>() == "", "");
    static_assert("H"_ss.substring<1, 1>() == "", "");
    static_assert("H"_ss.substring<0, 1>() == "H", "");
    static_assert("Hello"_ss.substring<0, 5>() == "Hello", "");
    static_assert("Hello"_ss.substring<3, 3>() == "", "");
    static_assert("Hello"_ss.substring<1, 5>() == "ello", "");
    static_assert("Hello"_ss.substring<0, 4>() == "Hell", "");
    static_assert("Hello"_ss.substring<2, 5>() == "llo", "");
    static_assert("Hello"_ss.substring<3, 4>() == "l", "");
    static_assert("Hello"_ss.substring<2, 4>() == "ll", "");
    static_assert("Hello"_ss.substring<1, 4>() == "ell", "");

    // prefix() tests
    static_assert(""_ss.prefix<0>() == "", "");
    static_assert("Hello"_ss.prefix<0>() == "", "");
    static_assert("Hello"_ss.prefix<1>() == "H", "");
    static_assert("Hello"_ss.prefix<2>() == "He", "");
    static_assert("Hello"_ss.prefix<3>() == "Hel", "");
    static_assert("Hello"_ss.prefix<4>() == "Hell", "");
    static_assert("Hello"_ss.prefix<5>() == "Hello", "");

    // suffix() tests
    static_assert(""_ss.suffix<0>() == "", "");
    static_assert("Hello"_ss.suffix<0>() == "Hello", "");
    static_assert("Hello"_ss.suffix<1>() == "ello", "");
    static_assert("Hello"_ss.suffix<2>() == "llo", "");
    static_assert("Hello"_ss.suffix<3>() == "lo", "");
    static_assert("Hello"_ss.suffix<4>() == "o", "");
    static_assert("Hello"_ss.suffix<5>() == "", "");

    // find(ch) tests
    static_assert(""_ss.find('a') == static_string::npos, "");
    static_assert("a"_ss.find('a') == 0, "");
    static_assert("b"_ss.find('a') == static_string::npos, "");
    static_assert("abcabca"_ss.find('a') == 0, "");
    static_assert("abcabca"_ss.find('a', 1) == 3, "");
    static_assert("abcabca"_ss.find('a', 4) == 6, "");
    static_assert("abcabca"_ss.find('a', 7) == static_string::npos, "");
    static_assert("abcabca"_ss.find('a', 1'000'000) == static_string::npos, "");
    static_assert("abcabca"_ss.find('a', 0, 0) == 0, "");
    static_assert("abcabca"_ss.find('a', 0, 1) == 3, "");
    static_assert("abcabca"_ss.find('a', 0, 2) == 6, "");
    static_assert("abcabca"_ss.find('a', 0, 3) == static_string::npos, "");
    static_assert("abcabca"_ss.find('a', 0, 1'000'000) == static_string::npos, "");

    // rfind(ch) tests
    static_assert(""_ss.rfind('c') == static_string::npos, "");
    static_assert("c"_ss.rfind('c') == 0, "");
    static_assert("b"_ss.rfind('c') == static_string::npos, "");
    static_assert("cabcabc"_ss.rfind('c') == 6, "");
    static_assert("cabcabc"_ss.rfind('c', 5) == 3, "");
    static_assert("cabcabc"_ss.rfind('c', 2) == 0, "");
    static_assert("cabcabc"_ss.rfind('c', -1) == static_string::npos, "");
    static_assert("cabcabc"_ss.rfind('c', 1'000'000) == static_string::npos, "");
    static_assert("cabcabc"_ss.rfind('c', 6, 0) == 6, "");
    static_assert("cabcabc"_ss.rfind('c', 6, 1) == 3, "");
    static_assert("cabcabc"_ss.rfind('c', 6, 2) == 0, "");
    static_assert("cabcabc"_ss.rfind('c', 6, 3) == static_string::npos, "");
    static_assert("cabcabc"_ss.rfind('c', 6, 1'000'000) == static_string::npos, "");

    // find(str) tests
    static_assert(""_ss.find("") == 0, "");
    static_assert(""_ss.find("", 1) == static_string::npos, "");
    static_assert(""_ss.find("", 0, 1) == static_string::npos, "");
    static_assert("a"_ss.find("") == 0, "");
    static_assert("a"_ss.find("", 1) == 1, "");
    static_assert("a"_ss.find("", 0, 1) == 1, "");
    static_assert(""_ss.find("a") == static_string::npos, "");
    static_assert(""_ss.find("a", 1) == static_string::npos, "");
    static_assert(""_ss.find("a", 0, 1) == static_string::npos, "");
    static_assert("a"_ss.find("a") == 0, "");
    static_assert("a"_ss.find("a", 1) == static_string::npos, "");
    static_assert("a"_ss.find("a", 0, 1) == static_string::npos, "");
    static_assert("aaaaa"_ss.find("aa") == 0, "");
    static_assert("aaaaa"_ss.find("aa", 1) == 1, "");
    static_assert("aaaaa"_ss.find("aa", 2) == 2, "");
    static_assert("aaaaa"_ss.find("aa", 3) == 3, "");
    static_assert("aaaaa"_ss.find("aa", 4) == static_string::npos, "");
    static_assert("aaaaa"_ss.find("aa", 0, 1) == 1, "");
    static_assert("aaaaa"_ss.find("aa", 0, 2) == 2, "");
    static_assert("aaaaa"_ss.find("aa", 0, 3) == 3, "");
    static_assert("aaaaa"_ss.find("aa", 0, 4) == static_string::npos, "");
    static_assert("aaaaa"_ss.find("aaaaa") == 0, "");
    static_assert("ababababa"_ss.find("ba") == 1, "");
    static_assert("ababababa"_ss.find("ba", 2) == 3, "");
    static_assert("ababababa"_ss.find("ba", 4) == 5, "");
    static_assert("ababababa"_ss.find("ba", 6) == 7, "");
    static_assert("ababababa"_ss.find("ba", 8) == static_string::npos, "");
    static_assert("ababababa"_ss.find("ba", 0, 1) == 3, "");
    static_assert("ababababa"_ss.find("ba", 0, 2) == 5, "");
    static_assert("ababababa"_ss.find("ba", 0, 3) == 7, "");
    static_assert("ababababa"_ss.find("ba", 0, 4) == static_string::npos, "");
    static_assert("ababababa"_ss.find("ababababa") == 0, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac") == 2, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac", 3) == 6, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac", 7) == 10, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac", 11) == 37, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac", 38) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac", 0, 1) == 6, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac", 0, 2) == 10, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac", 0, 3) == 37, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac", 0, 4) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("ccb") == 0, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("ccb", 1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("ccb", 0, 1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bdc") == 58, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bdc", 59) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bdc", 0, 1) == static_string::npos, "");
    static_assert(""_ss.find(""_ss) == 0, "");
    static_assert(""_ss.find(""_ss, 1) == static_string::npos, "");
    static_assert(""_ss.find(""_ss, 0, 1) == static_string::npos, "");
    static_assert("a"_ss.find(""_ss) == 0, "");
    static_assert("a"_ss.find(""_ss, 1) == 1, "");
    static_assert("a"_ss.find(""_ss, 0, 1) == 1, "");
    static_assert(""_ss.find("a"_ss) == static_string::npos, "");
    static_assert(""_ss.find("a"_ss, 1) == static_string::npos, "");
    static_assert(""_ss.find("a"_ss, 0, 1) == static_string::npos, "");
    static_assert("a"_ss.find("a"_ss) == 0, "");
    static_assert("a"_ss.find("a"_ss, 1) == static_string::npos, "");
    static_assert("a"_ss.find("a"_ss, 0, 1) == static_string::npos, "");
    static_assert("aaaaa"_ss.find("aa"_ss) == 0, "");
    static_assert("aaaaa"_ss.find("aa"_ss, 1) == 1, "");
    static_assert("aaaaa"_ss.find("aa"_ss, 2) == 2, "");
    static_assert("aaaaa"_ss.find("aa"_ss, 3) == 3, "");
    static_assert("aaaaa"_ss.find("aa"_ss, 4) == static_string::npos, "");
    static_assert("aaaaa"_ss.find("aa"_ss, 0, 1) == 1, "");
    static_assert("aaaaa"_ss.find("aa"_ss, 0, 2) == 2, "");
    static_assert("aaaaa"_ss.find("aa"_ss, 0, 3) == 3, "");
    static_assert("aaaaa"_ss.find("aa"_ss, 0, 4) == static_string::npos, "");
    static_assert("aaaaa"_ss.find("aaaaa"_ss) == 0, "");
    static_assert("ababababa"_ss.find("ba"_ss) == 1, "");
    static_assert("ababababa"_ss.find("ba"_ss, 2) == 3, "");
    static_assert("ababababa"_ss.find("ba"_ss, 4) == 5, "");
    static_assert("ababababa"_ss.find("ba"_ss, 6) == 7, "");
    static_assert("ababababa"_ss.find("ba"_ss, 8) == static_string::npos, "");
    static_assert("ababababa"_ss.find("ba"_ss, 0, 1) == 3, "");
    static_assert("ababababa"_ss.find("ba"_ss, 0, 2) == 5, "");
    static_assert("ababababa"_ss.find("ba"_ss, 0, 3) == 7, "");
    static_assert("ababababa"_ss.find("ba"_ss, 0, 4) == static_string::npos, "");
    static_assert("ababababa"_ss.find("ababababa"_ss) == 0, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss) == 2, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss, 3) == 6, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss, 7) == 10, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss, 11) == 37, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss, 38) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss, 0, 1) == 6, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss, 0, 2) == 10, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss, 0, 3) == 37, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bac"_ss, 0, 4) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("ccb"_ss) == 0, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("ccb"_ss, 1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("ccb"_ss, 0, 1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bdc"_ss) == 58, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bdc"_ss, 59) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.find("bdc"_ss, 0, 1) == static_string::npos, "");

    // static_string_rfind(str) tests
    static_assert(""_ss.rfind("") == 0, "");
    static_assert(""_ss.rfind("", 1) == static_string::npos, "");
    static_assert(""_ss.rfind("", 0, 1) == static_string::npos, "");
    static_assert("a"_ss.rfind("") == 1, "");
    static_assert("a"_ss.rfind("", 1) == 1, "");
    static_assert("a"_ss.rfind("", 0, 1) == static_string::npos, "");
    static_assert(""_ss.rfind("a") == static_string::npos, "");
    static_assert(""_ss.rfind("a", 1) == static_string::npos, "");
    static_assert(""_ss.rfind("a", 0, 1) == static_string::npos, "");
    static_assert("a"_ss.rfind("a") == 0, "");
    static_assert("a"_ss.rfind("a", 1) == static_string::npos, "");
    static_assert("a"_ss.rfind("a", 0, 1) == static_string::npos, "");
    static_assert("aaaaa"_ss.rfind("aa") == 3, "");
    static_assert("aaaaa"_ss.rfind("aa", 2) == 2, "");
    static_assert("aaaaa"_ss.rfind("aa", 1) == 1, "");
    static_assert("aaaaa"_ss.rfind("aa", 0) == 0, "");
    static_assert("aaaaa"_ss.rfind("aa", -1) == static_string::npos, "");
    static_assert("aaaaa"_ss.rfind("aa", 3, 1) == 2, "");
    static_assert("aaaaa"_ss.rfind("aa", 3, 2) == 1, "");
    static_assert("aaaaa"_ss.rfind("aa", 3, 3) == 0, "");
    static_assert("aaaaa"_ss.rfind("aa", 3, 4) == static_string::npos, "");
    static_assert("aaaaa"_ss.rfind("aaaaa") == 0, "");
    static_assert("ababababa"_ss.rfind("ba") == 7, "");
    static_assert("ababababa"_ss.rfind("ba", 6) == 5, "");
    static_assert("ababababa"_ss.rfind("ba", 4) == 3, "");
    static_assert("ababababa"_ss.rfind("ba", 2) == 1, "");
    static_assert("ababababa"_ss.rfind("ba", 0) == static_string::npos, "");
    static_assert("ababababa"_ss.rfind("ba", 7, 1) == 5, "");
    static_assert("ababababa"_ss.rfind("ba", 7, 2) == 3, "");
    static_assert("ababababa"_ss.rfind("ba", 7, 3) == 1, "");
    static_assert("ababababa"_ss.rfind("ba", 7, 4) == static_string::npos, "");
    static_assert("ababababa"_ss.rfind("ababababa") == 0, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac") == 37, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac", 36) == 10, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac", 9) == 6, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac", 5) == 2, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac", 1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac", 58, 1) == 10, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac", 58, 2) == 6, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac", 58, 3) == 2, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac", 58, 4) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("ccb") == 0, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("ccb", -1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("ccb", 58, 1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bdc") == 58, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bdc", 57) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bdc", 58, 1) == static_string::npos, "");
    static_assert(""_ss.rfind(""_ss) == 0, "");
    static_assert(""_ss.rfind(""_ss, 1) == static_string::npos, "");
    static_assert(""_ss.rfind(""_ss, 0, 1) == static_string::npos, "");
    static_assert("a"_ss.rfind(""_ss) == 1, "");
    static_assert("a"_ss.rfind(""_ss, 1) == 1, "");
    static_assert("a"_ss.rfind(""_ss, 0, 1) == static_string::npos, "");
    static_assert(""_ss.rfind("a"_ss) == static_string::npos, "");
    static_assert(""_ss.rfind("a"_ss, 1) == static_string::npos, "");
    static_assert(""_ss.rfind("a"_ss, 0, 1) == static_string::npos, "");
    static_assert("a"_ss.rfind("a"_ss) == 0, "");
    static_assert("a"_ss.rfind("a"_ss, 1) == static_string::npos, "");
    static_assert("a"_ss.rfind("a"_ss, 0, 1) == static_string::npos, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss) == 3, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss, 2) == 2, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss, 1) == 1, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss, 0) == 0, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss, -1) == static_string::npos, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss, 3, 1) == 2, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss, 3, 2) == 1, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss, 3, 3) == 0, "");
    static_assert("aaaaa"_ss.rfind("aa"_ss, 3, 4) == static_string::npos, "");
    static_assert("aaaaa"_ss.rfind("aaaaa"_ss) == 0, "");
    static_assert("ababababa"_ss.rfind("ba"_ss) == 7, "");
    static_assert("ababababa"_ss.rfind("ba"_ss, 6) == 5, "");
    static_assert("ababababa"_ss.rfind("ba"_ss, 4) == 3, "");
    static_assert("ababababa"_ss.rfind("ba"_ss, 2) == 1, "");
    static_assert("ababababa"_ss.rfind("ba"_ss, 0) == static_string::npos, "");
    static_assert("ababababa"_ss.rfind("ba"_ss, 7, 1) == 5, "");
    static_assert("ababababa"_ss.rfind("ba"_ss, 7, 2) == 3, "");
    static_assert("ababababa"_ss.rfind("ba"_ss, 7, 3) == 1, "");
    static_assert("ababababa"_ss.rfind("ba"_ss, 7, 4) == static_string::npos, "");
    static_assert("ababababa"_ss.rfind("ababababa"_ss) == 0, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss) == 37, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss, 36) == 10, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss, 9) == 6, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss, 5) == 2, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss, 1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss, 58, 1) == 10, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss, 58, 2) == 6, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss, 58, 3) == 2, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bac"_ss, 58, 4) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("ccb"_ss) == 0, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("ccb"_ss, -1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("ccb"_ss, 58, 1) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bdc"_ss) == 58, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bdc"_ss, 57) == static_string::npos, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.rfind("bdc"_ss, 58, 1) == static_string::npos, "");

    // contains(ch) tests
    static_assert(!""_ss.contains('a'), "");
    static_assert("a"_ss.contains('a'), "");
    static_assert(!"a"_ss.contains('b'), "");
    static_assert("cabcabc"_ss.contains('a'), "");
    static_assert("cabcabc"_ss.contains('b'), "");
    static_assert("cabcabc"_ss.contains('c'), "");
    static_assert(!"cabcabc"_ss.contains('e'), "");
    static_assert(!"cabcabc"_ss.contains('f'), "");
    static_assert(!"cabcabc"_ss.contains('g'), "");

    // contains(str) tests
    static_assert(""_ss.contains(""), "");
    static_assert("a"_ss.contains(""), "");
    static_assert(!""_ss.contains("a"), "");
    static_assert("a"_ss.contains("a"), "");
    static_assert(!"a"_ss.contains("b"), "");
    static_assert("cabcabc"_ss.contains("cab"), "");
    static_assert("cabcabc"_ss.contains("bca"), "");
    static_assert("cabcabc"_ss.contains("abc"), "");
    static_assert(!"cabcabc"_ss.contains("cba"), "");
    static_assert(!"cabcabc"_ss.contains("aca"), "");
    static_assert(!"cabcabc"_ss.contains("abb"), "");
    static_assert("cabcabc"_ss.contains("cabcabc"), "");
    static_assert(!"cabcabc"_ss.contains("cabcabca"), "");
    static_assert(!"cabcabc"_ss.contains("acabcabc"), "");
    static_assert(""_ss.contains(""_ss), "");
    static_assert("a"_ss.contains(""_ss), "");
    static_assert(!""_ss.contains("a"_ss), "");
    static_assert("a"_ss.contains("a"_ss), "");
    static_assert(!"a"_ss.contains("b"_ss), "");
    static_assert("cabcabc"_ss.contains("cab"_ss), "");
    static_assert("cabcabc"_ss.contains("bca"_ss), "");
    static_assert("cabcabc"_ss.contains("abc"_ss), "");
    static_assert(!"cabcabc"_ss.contains("cba"_ss), "");
    static_assert(!"cabcabc"_ss.contains("aca"_ss), "");
    static_assert(!"cabcabc"_ss.contains("abb"_ss), "");
    static_assert("cabcabc"_ss.contains("cabcabc"_ss), "");
    static_assert(!"cabcabc"_ss.contains("cabcabca"_ss), "");
    static_assert(!"cabcabc"_ss.contains("acabcabc"_ss), "");

    // static_string_count() tests
    static_assert(""_ss.count('a') == 0, "");
    static_assert("cdbcbdcbdcb"_ss.count('a') == 0, "");
    static_assert("a"_ss.count('a') == 1, "");
    static_assert("aa"_ss.count('a') == 2, "");
    static_assert("abcd"_ss.count('a') == 1, "");
    static_assert("abcd"_ss.count('b') == 1, "");
    static_assert("abcd"_ss.count('c') == 1, "");
    static_assert("abcd"_ss.count('d') == 1, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.count('a') == 15, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.count('b') == 13, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.count('c') == 17, "");
    static_assert("ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss.count('d') == 16, "");

    // starts_with() tests
    static_assert(""_ss.starts_with(""), "");
    static_assert("a"_ss.starts_with(""), "");
    static_assert(!""_ss.starts_with("a"), "");
    static_assert("a"_ss.starts_with("a"), "");
    static_assert(!"a"_ss.starts_with("b"), "");
    static_assert(!"a"_ss.starts_with("ab"), "");
    static_assert("abcabca"_ss.starts_with(""), "");
    static_assert("abcabca"_ss.starts_with("a"), "");
    static_assert("abcabca"_ss.starts_with("ab"), "");
    static_assert("abcabca"_ss.starts_with("abc"), "");
    static_assert("abcabca"_ss.starts_with("abca"), "");
    static_assert("abcabca"_ss.starts_with("abcab"), "");
    static_assert("abcabca"_ss.starts_with("abcabc"), "");
    static_assert("abcabca"_ss.starts_with("abcabca"), "");
    static_assert(!"abcabca"_ss.starts_with("abcabcab"), "");
    static_assert(!"abcabca"_ss.starts_with("bcabca"), "");
    static_assert(!"abcabca"_ss.starts_with("acabca"), "");
    static_assert(!"abcabca"_ss.starts_with("abcaba"), "");
    static_assert(""_ss.starts_with(""_ss), "");
    static_assert("a"_ss.starts_with(""_ss), "");
    static_assert(!""_ss.starts_with("a"_ss), "");
    static_assert("a"_ss.starts_with("a"_ss), "");
    static_assert(!"a"_ss.starts_with("b"_ss), "");
    static_assert(!"a"_ss.starts_with("ab"_ss), "");
    static_assert("abcabca"_ss.starts_with(""_ss), "");
    static_assert("abcabca"_ss.starts_with("a"_ss), "");
    static_assert("abcabca"_ss.starts_with("ab"_ss), "");
    static_assert("abcabca"_ss.starts_with("abc"_ss), "");
    static_assert("abcabca"_ss.starts_with("abca"_ss), "");
    static_assert("abcabca"_ss.starts_with("abcab"_ss), "");
    static_assert("abcabca"_ss.starts_with("abcabc"_ss), "");
    static_assert("abcabca"_ss.starts_with("abcabca"_ss), "");
    static_assert(!"abcabca"_ss.starts_with("abcabcab"_ss), "");
    static_assert(!"abcabca"_ss.starts_with("bcabca"_ss), "");
    static_assert(!"abcabca"_ss.starts_with("acabca"_ss), "");
    static_assert(!"abcabca"_ss.starts_with("abcaba"_ss), "");

    // ends_with() tests
    static_assert(""_ss.ends_with(""), "");
    static_assert("a"_ss.ends_with(""), "");
    static_assert(!""_ss.ends_with("a"), "");
    static_assert("a"_ss.ends_with("a"), "");
    static_assert(!"a"_ss.ends_with("b"), "");
    static_assert(!"a"_ss.ends_with("ba"), "");
    static_assert("abcabca"_ss.ends_with(""), "");
    static_assert("abcabca"_ss.ends_with("a"), "");
    static_assert("abcabca"_ss.ends_with("ca"), "");
    static_assert("abcabca"_ss.ends_with("bca"), "");
    static_assert("abcabca"_ss.ends_with("abca"), "");
    static_assert("abcabca"_ss.ends_with("cabca"), "");
    static_assert("abcabca"_ss.ends_with("bcabca"), "");
    static_assert("abcabca"_ss.ends_with("abcabca"), "");
    static_assert(!"abcabca"_ss.ends_with("babcabca"), "");
    static_assert(!"abcabca"_ss.ends_with("abcabc"), "");
    static_assert(!"abcabca"_ss.ends_with("abcaba"), "");
    static_assert(!"abcabca"_ss.ends_with("acabca"), "");
    static_assert(""_ss.ends_with(""_ss), "");
    static_assert("a"_ss.ends_with(""_ss), "");
    static_assert(!""_ss.ends_with("a"_ss), "");
    static_assert("a"_ss.ends_with("a"_ss), "");
    static_assert(!"a"_ss.ends_with("b"_ss), "");
    static_assert(!"a"_ss.ends_with("ba"_ss), "");
    static_assert("abcabca"_ss.ends_with(""_ss), "");
    static_assert("abcabca"_ss.ends_with("a"_ss), "");
    static_assert("abcabca"_ss.ends_with("ca"_ss), "");
    static_assert("abcabca"_ss.ends_with("bca"_ss), "");
    static_assert("abcabca"_ss.ends_with("abca"_ss), "");
    static_assert("abcabca"_ss.ends_with("cabca"_ss), "");
    static_assert("abcabca"_ss.ends_with("bcabca"_ss), "");
    static_assert("abcabca"_ss.ends_with("abcabca"_ss), "");
    static_assert(!"abcabca"_ss.ends_with("babcabca"_ss), "");
    static_assert(!"abcabca"_ss.ends_with("abcabc"_ss), "");
    static_assert(!"abcabca"_ss.ends_with("abcaba"_ss), "");
    static_assert(!"abcabca"_ss.ends_with("acabca"_ss), "");

    // lower() tests
    static_assert(""_ss.lower() == "", "");
    static_assert("H"_ss.lower() == "h", "");
    static_assert("He"_ss.lower() == "he", "");
    static_assert("HeLlO"_ss.lower() == "hello", "");
    static_assert("abcABCxyzXYZ"_ss.lower() == "abcabcxyzxyz", "");

    // upper() tests
    static_assert(""_ss.upper() == "", "");
    static_assert("h"_ss.upper() == "H", "");
    static_assert("He"_ss.upper() == "HE", "");
    static_assert("HeLlO"_ss.upper() == "HELLO", "");
    static_assert("abcABCxyzXYZ"_ss.upper() == "ABCABCXYZXYZ", "");

    { // split() tests
        constexpr auto ss = "abracadabra"_ss;
        static_assert(ss.split<5>() == std::make_pair("abrac"_ss, "dabra"_ss), "");
        static_assert(ss.split<ss.find('a')>() == std::make_pair(""_ss, "bracadabra"_ss), "");
        static_assert(ss.split<ss.find('a', 0, 3)>() == std::make_pair("abracad"_ss, "bra"_ss), "");
        static_assert(ss.split<ss.find('d')>() == std::make_pair("abraca"_ss, "abra"_ss), "");
        static_assert(ss.split<ss.find('b')>() == std::make_pair("a"_ss, "racadabra"_ss), "");
        static_assert(ss.split<ss.rfind('b')>() == std::make_pair("abracada"_ss, "ra"_ss), "");
    }

    // hash() tests
    static_assert(""_ss.hash() == 5381ULL, "");
    static_assert("Hello"_ss.hash() == 210724412158ULL, "");
    static_assert("HelloWorld"_ss.hash() == 8246272427518117483ULL, "");
    static_assert("HelloWorldHelloWorld"_ss.hash() == 889607825945456465ULL, "");

    // ITOSS() tests
    static_assert(ITOSS(0) == "0", "");
    static_assert(ITOSS(1) == "1", "");
    static_assert(ITOSS(9) == "9", "");
    static_assert(ITOSS(10) == "10", "");
    static_assert(ITOSS(11) == "11", "");
    static_assert(ITOSS(14) == "14", "");
    static_assert(ITOSS(19) == "19", "");
    static_assert(ITOSS(99) == "99", "");
    static_assert(ITOSS(873) == "873", "");
    static_assert(ITOSS(496850) == "496850", "");
    static_assert(ITOSS(853104678) == "853104678", "");
    static_assert(ITOSS(2147483647) == "2147483647", "");
    static_assert(ITOSS(4294967295LL) == "4294967295", "");
    static_assert(ITOSS(827394274920LL) == "827394274920", "");
    static_assert(ITOSS(294653986395673LL) == "294653986395673", "");
    static_assert(ITOSS(973946584364859472LL) == "973946584364859472", "");
    static_assert(ITOSS(9223372036854775807LL) == "9223372036854775807", "");
    static_assert(ITOSS(std::numeric_limits<long long>::max()) == "9223372036854775807", "");
    static_assert(ITOSS(-1) == "-1", "");
    static_assert(ITOSS(-9) == "-9", "");
    static_assert(ITOSS(-10) == "-10", "");
    static_assert(ITOSS(-11) == "-11", "");
    static_assert(ITOSS(-14) == "-14", "");
    static_assert(ITOSS(-19) == "-19", "");
    static_assert(ITOSS(-99) == "-99", "");
    static_assert(ITOSS(-873) == "-873", "");
    static_assert(ITOSS(-496850) == "-496850", "");
    static_assert(ITOSS(-853104678) == "-853104678", "");
    static_assert(ITOSS(-2147483647) == "-2147483647", "");
    static_assert(ITOSS(-4294967295LL) == "-4294967295", "");
    static_assert(ITOSS(-827394274920LL) == "-827394274920", "");
    static_assert(ITOSS(-294653986395673LL) == "-294653986395673", "");
    static_assert(ITOSS(-973946584364859472LL) == "-973946584364859472", "");
    static_assert(ITOSS(-9223372036854775807LL) == "-9223372036854775807", "");
    static_assert(ITOSS(std::numeric_limits<long long>::min()) == "-9223372036854775808", "");

    // UTOSS() tests
    static_assert(UTOSS(0) == "0", "");
    static_assert(UTOSS(1) == "1", "");
    static_assert(UTOSS(9) == "9", "");
    static_assert(UTOSS(10) == "10", "");
    static_assert(UTOSS(11) == "11", "");
    static_assert(UTOSS(14) == "14", "");
    static_assert(UTOSS(19) == "19", "");
    static_assert(UTOSS(99) == "99", "");
    static_assert(UTOSS(873) == "873", "");
    static_assert(UTOSS(496850) == "496850", "");
    static_assert(UTOSS(853104678) == "853104678", "");
    static_assert(UTOSS(2147483647) == "2147483647", "");
    static_assert(UTOSS(4294967295ULL) == "4294967295", "");
    static_assert(UTOSS(827394274920ULL) == "827394274920", "");
    static_assert(UTOSS(294653986395673ULL) == "294653986395673", "");
    static_assert(UTOSS(973946584364859472ULL) == "973946584364859472", "");
    static_assert(UTOSS(9223372036854775807ULL) == "9223372036854775807", "");
    static_assert(UTOSS(18446744073709551615ULL) == "18446744073709551615", "");
    static_assert(UTOSS(std::numeric_limits<unsigned long long>::max()) == "18446744073709551615", "");

    // SSTOI() tests
    static_assert(SSTOI("") == 0, "");
    static_assert(SSTOI("0") == 0, "");
    static_assert(SSTOI("1") == 1, "");
    static_assert(SSTOI("9") == 9, "");
    static_assert(SSTOI("10") == 10, "");
    static_assert(SSTOI("11") == 11, "");
    static_assert(SSTOI("14") == 14, "");
    static_assert(SSTOI("19") == 19, "");
    static_assert(SSTOI("99") == 99, "");
    static_assert(SSTOI("873") == 873, "");
    static_assert(SSTOI("496850") == 496850, "");
    static_assert(SSTOI("853104678") == 853104678, "");
    static_assert(SSTOI("2147483647") == 2147483647, "");
    static_assert(SSTOI("4294967295") == 4294967295LL, "");
    static_assert(SSTOI("827394274920") == 827394274920LL, "");
    static_assert(SSTOI("294653986395673") == 294653986395673LL, "");
    static_assert(SSTOI("973946584364859472") == 973946584364859472LL, "");
    static_assert(SSTOI("9223372036854775807") == 9223372036854775807LL, "");
    static_assert(SSTOI("9223372036854775807") == std::numeric_limits<long long>::max(), "");
    static_assert(SSTOI("-1") == -1, "");
    static_assert(SSTOI("-9") == -9, "");
    static_assert(SSTOI("-10") == -10, "");
    static_assert(SSTOI("-11") == -11, "");
    static_assert(SSTOI("-14") == -14, "");
    static_assert(SSTOI("-19") == -19, "");
    static_assert(SSTOI("-99") == -99, "");
    static_assert(SSTOI("-873") == -873, "");
    static_assert(SSTOI("-496850") == -496850, "");
    static_assert(SSTOI("-853104678") == -853104678, "");
    static_assert(SSTOI("-2147483647") == -2147483647, "");
    static_assert(SSTOI("-4294967295") == -4294967295LL, "");
    static_assert(SSTOI("-827394274920") == -827394274920LL, "");
    static_assert(SSTOI("-294653986395673") == -294653986395673LL, "");
    static_assert(SSTOI("-973946584364859472") == -973946584364859472LL, "");
    static_assert(SSTOI("-9223372036854775807") == -9223372036854775807LL, "");
    static_assert(SSTOI("-9223372036854775808") == std::numeric_limits<long long>::min(), "");

    // SSTOU() tests
    static_assert(SSTOU("") == 0, "");
    static_assert(SSTOU("0") == 0, "");
    static_assert(SSTOI("1") == 1, "");
    static_assert(SSTOU("9") == 9, "");
    static_assert(SSTOU("10") == 10, "");
    static_assert(SSTOU("11") == 11, "");
    static_assert(SSTOU("14") == 14, "");
    static_assert(SSTOU("19") == 19, "");
    static_assert(SSTOU("99") == 99, "");
    static_assert(SSTOU("873") == 873, "");
    static_assert(SSTOU("496850") == 496850, "");
    static_assert(SSTOU("853104678") == 853104678, "");
    static_assert(SSTOU("2147483647") == 2147483647, "");
    static_assert(SSTOU("4294967295") == 4294967295ULL, "");
    static_assert(SSTOU("827394274920") == 827394274920ULL, "");
    static_assert(SSTOU("294653986395673") == 294653986395673ULL, "");
    static_assert(SSTOU("973946584364859472") == 973946584364859472ULL, "");
    static_assert(SSTOU("9223372036854775807") == 9223372036854775807ULL, "");
    static_assert(SSTOU("18446744073709551615") == 18446744073709551615ULL, "");
    static_assert(SSTOU("18446744073709551615") == std::numeric_limits<unsigned long long>::max(), "");

    { // struct methods tests
        constexpr auto ss0 = ""_ss;
        static_assert(ss0.empty(), "");
        static_assert(ss0.length() == 0, "");
        static_assert(ss0.size() == 0, "");
        static_assert(sizeof(ss0) == 1, "");
        static_assert(ss0.reverse() == "", "");
        static_assert(ss0.substring<0, 0>() == "", "");
        static_assert(ss0.prefix<0>() == "", "");
        static_assert(ss0.suffix<0>() == "", "");
        constexpr auto ss1 = "Hello"_ss;
        static_assert(!ss1.empty(), "");
        static_assert(ss1.length() == 5, "");
        static_assert(ss1.size() == 5, "");
        static_assert(sizeof(ss1) == 6, "");
        static_assert(ss1.reverse() == "olleH", "");
        static_assert(ss1.substring<0, 5>() == "Hello", "");
        static_assert(ss1.substring<3, 3>() == "", "");
        static_assert(ss1.substring<1, 5>() == "ello", "");
        static_assert(ss1.substring<0, 4>() == "Hell", "");
        static_assert(ss1.substring<2, 5>() == "llo", "");
        static_assert(ss1.substring<3, 4>() == "l", "");
        static_assert(ss1.substring<2, 4>() == "ll", "");
        static_assert(ss1.substring<1, 4>() == "ell", "");
        static_assert(ss1.prefix<0>() == "", "");
        static_assert(ss1.prefix<1>() == "H", "");
        static_assert(ss1.prefix<2>() == "He", "");
        static_assert(ss1.prefix<3>() == "Hel", "");
        static_assert(ss1.prefix<4>() == "Hell", "");
        static_assert(ss1.prefix<5>() == "Hello", "");
        static_assert(ss1.suffix<0>() == "Hello", "");
        static_assert(ss1.suffix<1>() == "ello", "");
        static_assert(ss1.suffix<2>() == "llo", "");
        static_assert(ss1.suffix<3>() == "lo", "");
        static_assert(ss1.suffix<4>() == "o", "");
        static_assert(ss1.suffix<5>() == "", "");
        constexpr auto ss2 = "abcabca"_ss;
        static_assert(ss2.find('a') == 0, "");
        static_assert(ss2.find('a', ss2.begin()) == 0, "");
        static_assert(ss2.find('a', ss2.end()) == static_string::npos, "");
        static_assert(ss2.find('a', 0) == 0, "");
        static_assert(ss2.find('a', 1) == 3, "");
        static_assert(ss2.find('a', 4) == 6, "");
        static_assert(ss2.find('a', 7) == static_string::npos, "");
        static_assert(ss2.find('a', 1'000'000) == static_string::npos, "");
        static_assert(ss2.find('a', ss2.begin(), 0) == 0, "");
        static_assert(ss2.find('a', ss2.begin(), 1) == 3, "");
        static_assert(ss2.find('a', ss2.begin(), 2) == 6, "");
        static_assert(ss2.find('a', ss2.begin(), 3) == static_string::npos, "");
        static_assert(ss2.find('a', ss2.begin(), 1'000'000) == static_string::npos, "");
        constexpr auto ss3 = "cabcabc"_ss;
        static_assert(ss3.rfind('c') == 6, "");
        static_assert(ss3.rfind('c', ss3.rbegin()) == 6, "");
        static_assert(ss3.rfind('c', ss3.rend()) == static_string::npos, "");
        static_assert(ss3.rfind('c', 6) == 6, "");
        static_assert(ss3.rfind('c', 5) == 3, "");
        static_assert(ss3.rfind('c', 2) == 0, "");
        static_assert(ss3.rfind('c', -1) == static_string::npos, "");
        static_assert(ss3.rfind('c', 1'000'000) == static_string::npos, "");
        static_assert(ss3.rfind('c', ss3.rbegin(), 0) == 6, "");
        static_assert(ss3.rfind('c', ss3.rbegin(), 1) == 3, "");
        static_assert(ss3.rfind('c', ss3.rbegin(), 2) == 0, "");
        static_assert(ss3.rfind('c', ss3.rbegin(), 3) == static_string::npos, "");
        static_assert(ss3.rfind('c', ss3.rbegin(), 1'000'000) == static_string::npos, "");
        static_assert(""_ss.hash() == 5381ULL, "");
        static_assert("Hello"_ss.hash() == 210724412158ULL, "");
        static_assert("HelloWorld"_ss.hash() == 8246272427518117483ULL, "");
        static_assert("HelloWorldHelloWorld"_ss.hash() == 889607825945456465ULL, "");
        static_assert(ss3[0] == 'c', "");
        static_assert(ss3[1] == 'a', "");
        static_assert(ss3[2] == 'b', "");
        static_assert(ss3[3] == 'c', "");
        static_assert(ss3[4] == 'a', "");
        static_assert(ss3[5] == 'b', "");
        static_assert(ss3[6] == 'c', "");
        static_assert(ss3[7] == '\0', "");
        constexpr auto ss4 = "ccbacdbacdbacdbdacbdacdacbdacdcbdadcabacbadcbdacdabcdabcdabdc"_ss;
        static_assert(ss4.count('a') == 15, "");
        static_assert(ss4.count('b') == 13, "");
        static_assert(ss4.count('c') == 17, "");
        static_assert(ss4.count('d') == 16, "");
        static_assert(ss4.count('a') + ss4.count('b') + ss4.count('c') + ss4.count('d') == ss4.length(), "");
        static_assert(ss2.starts_with(""), "");
        static_assert(ss2.starts_with("a"), "");
        static_assert(ss2.starts_with("ab"), "");
        static_assert(ss2.starts_with("abc"), "");
        static_assert(ss2.starts_with("abca"), "");
        static_assert(ss2.starts_with("abcab"), "");
        static_assert(ss2.starts_with("abcabc"), "");
        static_assert(ss2.starts_with("abcabca"), "");
        static_assert(!ss2.starts_with("abcabcab"), "");
        static_assert(!ss2.starts_with("bcabca"), "");
        static_assert(!ss2.starts_with("acabca"), "");
        static_assert(!ss2.starts_with("abcaba"), "");
        static_assert(ss2.starts_with(""_ss), "");
        static_assert(ss2.starts_with("a"_ss), "");
        static_assert(ss2.starts_with("ab"_ss), "");
        static_assert(ss2.starts_with("abc"_ss), "");
        static_assert(ss2.starts_with("abca"_ss), "");
        static_assert(ss2.starts_with("abcab"_ss), "");
        static_assert(ss2.starts_with("abcabc"_ss), "");
        static_assert(ss2.starts_with("abcabca"_ss), "");
        static_assert(!ss2.starts_with("abcabcab"_ss), "");
        static_assert(!ss2.starts_with("bcabca"_ss), "");
        static_assert(!ss2.starts_with("acabca"_ss), "");
        static_assert(!ss2.starts_with("abcaba"_ss), "");
        static_assert(ss2.ends_with(""), "");
        static_assert(ss2.ends_with("a"), "");
        static_assert(ss2.ends_with("ca"), "");
        static_assert(ss2.ends_with("bca"), "");
        static_assert(ss2.ends_with("abca"), "");
        static_assert(ss2.ends_with("cabca"), "");
        static_assert(ss2.ends_with("bcabca"), "");
        static_assert(ss2.ends_with("abcabca"), "");
        static_assert(!ss2.ends_with("babcabca"), "");
        static_assert(!ss2.ends_with("abcabc"), "");
        static_assert(!ss2.ends_with("abcaba"), "");
        static_assert(!ss2.ends_with("acabca"), "");
        static_assert(ss2.ends_with(""_ss), "");
        static_assert(ss2.ends_with("a"_ss), "");
        static_assert(ss2.ends_with("ca"_ss), "");
        static_assert(ss2.ends_with("bca"_ss), "");
        static_assert(ss2.ends_with("abca"_ss), "");
        static_assert(ss2.ends_with("cabca"_ss), "");
        static_assert(ss2.ends_with("bcabca"_ss), "");
        static_assert(ss2.ends_with("abcabca"_ss), "");
        static_assert(!ss2.ends_with("babcabca"_ss), "");
        static_assert(!ss2.ends_with("abcabc"_ss), "");
        static_assert(!ss2.ends_with("abcaba"_ss), "");
        static_assert(!ss2.ends_with("acabca"_ss), "");
        constexpr auto sss4 = "bac"_ss;
        static_assert(ss4.find("bac") == 2, "");
        static_assert(ss4.find("bac", 3) == 6, "");
        static_assert(ss4.find("bac", 7) == 10, "");
        static_assert(ss4.find("bac", 11) == 37, "");
        static_assert(ss4.find("bac", 38) == static_string::npos, "");
        static_assert(ss4.find("bac", ss4.begin(), 1) == 6, "");
        static_assert(ss4.find("bac", ss4.begin(), 2) == 10, "");
        static_assert(ss4.find("bac", ss4.begin(), 3) == 37, "");
        static_assert(ss4.find("bac", ss4.begin(), 4) == static_string::npos, "");
        static_assert(ss4.find(sss4) == 2, "");
        static_assert(ss4.find(sss4, 3) == 6, "");
        static_assert(ss4.find(sss4, 7) == 10, "");
        static_assert(ss4.find(sss4, 11) == 37, "");
        static_assert(ss4.find(sss4, 38) == static_string::npos, "");
        static_assert(ss4.find(sss4, ss4.begin(), 1) == 6, "");
        static_assert(ss4.find(sss4, ss4.begin(), 2) == 10, "");
        static_assert(ss4.find(sss4, ss4.begin(), 3) == 37, "");
        static_assert(ss4.find(sss4, ss4.begin(), 4) == static_string::npos, "");
        static_assert(ss4.rfind("bac") == 37, "");
        static_assert(ss4.rfind("bac", 36) == 10, "");
        static_assert(ss4.rfind("bac", 9) == 6, "");
        static_assert(ss4.rfind("bac", 5) == 2, "");
        static_assert(ss4.rfind("bac", 1) == static_string::npos, "");
        static_assert(ss4.rfind("bac", ss4.rbegin() - 2, 1) == 10, "");
        static_assert(ss4.rfind("bac", ss4.rbegin() - 2, 2) == 6, "");
        static_assert(ss4.rfind("bac", ss4.rbegin() - 2, 3) == 2, "");
        static_assert(ss4.rfind("bac", ss4.rbegin() - 2, 4) == static_string::npos, "");
        static_assert(ss4.rfind(sss4) == 37, "");
        static_assert(ss4.rfind(sss4, 36) == 10, "");
        static_assert(ss4.rfind(sss4, 9) == 6, "");
        static_assert(ss4.rfind(sss4, 5) == 2, "");
        static_assert(ss4.rfind(sss4, 1) == static_string::npos, "");
        static_assert(ss4.rfind(sss4, ss4.rbegin() - sss4.rbegin(), 1) == 10, "");
        static_assert(ss4.rfind(sss4, ss4.rbegin() - sss4.rbegin(), 2) == 6, "");
        static_assert(ss4.rfind(sss4, ss4.rbegin() - sss4.rbegin(), 3) == 2, "");
        static_assert(ss4.rfind(sss4, ss4.rbegin() - sss4.rbegin(), 4) == static_string::npos, "");
        static_assert(ss3.contains('a'), "");
        static_assert(ss3.contains('b'), "");
        static_assert(ss3.contains('c'), "");
        static_assert(!ss3.contains('e'), "");
        static_assert(!ss3.contains('f'), "");
        static_assert(!ss3.contains('g'), "");
        static_assert(ss3.contains("cab"), "");
        static_assert(ss3.contains("bca"), "");
        static_assert(ss3.contains("abc"), "");
        static_assert(!ss3.contains("cba"), "");
        static_assert(!ss3.contains("aca"), "");
        static_assert(!ss3.contains("abb"), "");
        static_assert(ss3.contains("cabcabc"), "");
        static_assert(!ss3.contains("cabcabca"), "");
        static_assert(!ss3.contains("acabcabc"), "");
    }

    // example #0
    std::cout << "Hello "_ss + "World!" << std::endl;

    { // example #1
        constexpr wchar_t name[] = L"Andrew";
        constexpr auto str1 = static_wstring::make(L"Hello, ", name, L"!");
        static_assert(str1 == L"Hello, Andrew!", "");
        std::wcout << str1 << std::endl;
    }

    { // example #2
        constexpr char country[] = "Great Britain";
        constexpr char captital[] = "London";
        constexpr auto str2 = static_string::make(captital, " is a capital of ", country);
        static_assert(str2 == "London is a capital of Great Britain", "");
        std::cout << str2 << std::endl;
    }

    { // example #3
        constexpr int apples = 5;
        constexpr int oranges = 7;
        constexpr int fruits = apples + oranges;
        constexpr auto str3 = static_wstring::make(L"I have ", ITOSW(apples), L" apples and ",
            ITOSW(oranges), L" oranges, so I have ", ITOSW(fruits), L" fruits");
        static_assert(str3 == L"I have 5 apples and 7 oranges, so I have 12 fruits", "");
        std::wcout << str3 << std::endl;
    }

    { // example #4
        constexpr auto sstr = static_string::make("1 + 1 = ", ITOSS(1 + 1));
        constexpr auto sstr1 = static_string::make(sstr, ", 2 + 2 = ", ITOSS(2 + 2));
        static_assert(sstr == "1 + 1 = 2", "");
        static_assert(sstr1 == "1 + 1 = 2, 2 + 2 = 4", "");
        std::string str = sstr1.str();
        std::cout << str << std::endl;
    }

    { // example #5
        constexpr auto sstr2 = "abcdefgh"_ss;
        for (size_t i = sstr2.begin(); i != sstr2.end(); ++i)
            std::cout << sstr2[i];
        std::cout << std::endl;
        for (size_t i = sstr2.rbegin(); i != sstr2.rend(); --i)
            std::cout << sstr2[i];
        std::cout << std::endl;
    }

    return 0;
}
